### ISSUE TITLE
A little too greedy for mech parts

### ISSUE THREAD

**Issue by Liakmad** [IceRaptor/LootMagnet#1]
No way Darius negotiated _that_ bad.
Is it intentional that only mechs are held back?
![image](https://user-images.githubusercontent.com/1049751/53661107-a1cbc300-3c70-11e9-9a1f-0199af582916.png)
[loot_magnet.log](https://github.com/IceRaptor/LootMagnet/files/2920790/loot_magnet.log)

**Comment by DeltaIII** [comment]
I'm not one of the devs for this mod, but looking at the code I think this might be symptom of the current way that Helper.HoldbackSalvage calculates the number of held back items (Helper.cs lines 96-102) . It is currently is purely based on the total size of the salvage list, so it _looks_ unreasonably brutal in RogueTech because the size of the loot table will often be large (more items means more stuff held back). If you factor in the relative ratio of "good-stuff" to "bad-stuff" and you get an issue where a large number mech-parts and/or high value internal parts are held back, even on low holdback chances (e.g. a 10% roll on a 50 item loot table will average at 5 items held back).  I think that is what you are seeing here!

Perhaps the mod devs could modify how the number of heldback items is calculated to be capped? Maybe based on the contract negotiation, so that larger loot tables are less punishing on players!!

**Comment by DeltaIII** [comment]
Actually, thinking about this some more, I think capping the number won't be enough. Because of the way the statistics works ([Binomial distribution](https://en.wikipedia.org/wiki/Binomial_distribution) here) I would anticipate that most players will see at least one mech part held back in almost all missions using the current code.
 
E.g. The chance to see _at least_ a certain number of items held back (calculated using [this website](https://stattrek.com/online-calculator/binomial.aspx)) assuming _only_ a 1% holdback chance:
                        
Loot table size  | 1+ item held | 2+ held | 3+ held | 4+ held 
--------------- | ------------ | ------ | ------ | -------
20 | 18.2% | 1.7% | 0.1% | almost 0%
40 | 33.1% | 6.1% | 0.7% | 0.1%
60 | 45.3% | 12.1 % | 2.2% | 0.3%
80 | 55.2% | 19.1% | 4.7% | 0.9%

And those numbers are for a 1% holdback chance, not 10+%! So I would expect that the current logic will make most players see a loss of _at least 1 mech part_ in _almost every_ mission until they get some _really_ good rep! The same table for 10% (start of a new game basically):

Loot table size  | 1+ item held | 2+ held | 3+ held | 4+ held 
--------------- | ------------ | ------ | ------ | -------
20 | 87.8% | 60.8% | 32.3% | 13.3%
40 | 98.5% | 91.9% | 77.7% | 57.7%
60 | 99.8% | 98.6 % | 94.7% | 86.3%
80 | almost 100% | 99.8% | 98.9% | 96.5%

I read this second table as losing all the mech parts from an assassination target 90+% of the time in the early game, feels bad man!

**Comment by Liakmad** [comment]
Yes, DeltaIII, that correlate with what i see on my current playthrough. And it's looks like partial mech salvage bundles up before being held back, so even if you headshot 3 mechs (4 pieces in 5-piece-to-rebuild setting) and loot screen holdback message shows three partial mech salvage being removed, all 12 pieces are gone.

I also believe it would be better to use two different holdback queues, for mech parts and for everyting else, with different settings. Not so keen on emploer to hold back Locust's parts when there is an Engine XL(C) collecting dust in pile of Mlasers.

**Comment by IceRaptor** [comment]
Yes, it's intentional that the most valuable parts are held back first. In most cases, that's going to be mech parts. However, LM does not currently split the partial mech price by the # of parts required to assemble a full mech, so the values are overly-inflated at the moment.

I've made significant changes in 2.0, with the game consistently taking 2-6 parts when holdback is triggered. However, holdback is triggered infrequently when you are friendly. Once 2.0 drops I'd encourage you to check it out and see if it addresses your complaints.

Thanks for the report!
